services:

  webserver:
    image: mariyo/php:8.2-apache-dev
    network_mode: bridge
    ports:
      - "8000:8000"
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chrome:
    network_mode: bridge
    image: selenium/standalone-chrome:132.0
    shm_size: 2gb
    links:
      - webserver
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:4444/wd/hub/status || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 5
